# Generated by Django 4.0.6 on 2022-07-18 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'created_at', 'ordering': ['expiry_date'], 'verbose_name': 'Task'},
        ),
        migrations.AlterField(
            model_name='task',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 11, 59, 11, 81974)),
        ),
    ]
