# Generated by Django 4.0.6 on 2022-07-14 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='last name')),
                ('picture', models.ImageField(blank=True, default='profile/default_user.png', null=True, upload_to='profile', verbose_name='profile picture')),
                ('bio', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'user-profile',
                'verbose_name_plural': 'user-profiles',
            },
        ),
    ]
