# Generated by Django 4.0.6 on 2022-08-15 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 17), null=True),
        ),
    ]
