# Generated by Django 4.0.6 on 2023-07-28 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 7, 29), null=True),
        ),
    ]
